# -*- coding: utf-8 -*-
"""pinecone-introduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VS1CWbHLaGWIJ-IMGq27rx6ld4u4hSJ
"""

!pip install pinecone

import pinecone
from pinecone import Pinecone, ServerlessSpec
import os

import os
from getpass import getpass

os.environ["PINECONE_API_KEY"] = os.getenv("PINECONE_API_KEY") or getpass(
    "Enter PineCone API Key: "
)

pc = Pinecone(api_key=os.environ["PINECONE_API_KEY"], environment = 'gcp-starter')

pc.list_indexes()

pc.list_indexes()

index_name = 'my-index'
for index in pc.list_indexes():
    if index.name == index_name:
        pc.delete_index(index_name)
        print(f"{index_name} Deleted successfully")
    else:
        print(f"{index_name} does not exist")

pc.list_indexes()

pc.create_index(
    name = 'new-index',
    dimension = 3,
    metric = 'cosine',
    spec = ServerlessSpec(
        cloud = "aws",
        region = "us-east-1")
    )

pc.list_indexes()

index = pc.Index('new-index')

index.upsert([
    ("Dog", [4., 0., 1.]),
    ("Pussy Cat", [4., 0., 1.]),
    ("Elephant", [4., 0., 1.]),
    ("Octopussy", [8., 0., 0.]),
    ("Human", [2., 0., 0.]),
    ("Monkey", [2., 0., 1.]),
    ("Chicken", [2., 2., 1.]),
    ("Duck", [2., 2., 1.]),
    ("Dinosaur", [4., 0., 1.]),

])

